name: macOS

on:
  push:
    branches:
      - main
  pull_request:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compilation
        run: |
          cmake .
          make clean
          make
      - name: make.sh
        run: |
          cmake . -DTEST=ON
          make test
          make clean
