name: ubuntu

on:
  push:
    branches:
      - main
  pull_request:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compilation
        run: |
          make
          make clean
      - name: test
        run: |
          make clean
          make test
          make clean
          make func
          make clean
